# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-31 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('LycuMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuaris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_usuari', models.CharField(max_length=20)),
                ('contrasenya', models.CharField(max_length=20)),
                ('correu', models.CharField(max_length=50)),
                ('permissos', models.BooleanField(default=False)),
                ('usuari_a_vots', models.ManyToManyField(through='LycuMain.Vots', to='LycuMain.Curiositat')),
            ],
        ),
    ]
