# Generated by Django 2.1.3 on 2019-01-30 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuaris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_usuari', models.CharField(max_length=20)),
                ('contrasenya', models.CharField(max_length=20)),
                ('correu', models.CharField(max_length=50)),
                ('permissos', models.BooleanField(default=False)),
            ],
        ),
    ]
