# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-01 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuari', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuaris',
            name='correu',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usuaris',
            name='nom_usuari',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
