# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 19:20
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('LycuMain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='novaSessio',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Usuaris',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correu', models.CharField(max_length=50, unique=True)),
                ('imatge_perfil', models.ImageField(blank=True, default='../../media/Perfil_Usuari/Usuari_default.png', upload_to='Perfil_Usuari/')),
                ('comentari_a_usuari', models.ManyToManyField(through='LycuMain.Comentari', to='Usuari.Usuaris')),
                ('usuari', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
