# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comentari',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contingut', models.CharField(max_length=500)),
                ('data_comentari', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Curiositat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titol', models.CharField(max_length=40, unique=True)),
                ('imatge', models.ImageField(upload_to='Imatges/')),
                ('contingut', models.CharField(max_length=5000)),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('estat', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ha_votat', models.BooleanField(default=False)),
                ('tipus', models.BooleanField(default=False)),
                ('curiositat_votada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LycuMain.Curiositat')),
            ],
        ),
    ]
