# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-10 19:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Usuari', '0001_initial'),
        ('LycuMain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vot',
            name='usuari_vota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuari.Usuaris'),
        ),
        migrations.AddField(
            model_name='curiositat',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuari.Usuaris'),
        ),
        migrations.AddField(
            model_name='curiositat',
            name='categoria_a_cusiositat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LycuMain.Categoria'),
        ),
        migrations.AddField(
            model_name='curiositat',
            name='usuari_a_vot',
            field=models.ManyToManyField(through='LycuMain.Vot', to='LycuMain.Curiositat'),
        ),
        migrations.AddField(
            model_name='comentari',
            name='curiositat_comentada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LycuMain.Curiositat'),
        ),
        migrations.AddField(
            model_name='comentari',
            name='usuari_comenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuari.Usuaris'),
        ),
    ]
