# Generated by Django 2.1.3 on 2019-01-30 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LycuMain', '0002_auto_20190130_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentari',
            name='usuari_comenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuari.Usuaris'),
        ),
    ]
