# Generated by Django 2.1.3 on 2019-01-30 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LycuMain', '0003_auto_20190130_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentari',
            name='usuari_comenta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Usuari.Usuaris'),
        ),
    ]
