# Generated by Django 2.1.3 on 2019-01-30 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LycuMain', '0004_auto_20190130_1743'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vots',
        ),
    ]
