# Generated by Django 2.1.3 on 2019-01-30 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LycuMain', '0005_delete_vots'),
    ]

    operations = [
        migrations.AddField(
            model_name='curiositat',
            name='categoria_a_cusiositat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='LycuMain.Categoria'),
        ),
    ]
