# Generated by Django 2.1.3 on 2019-01-30 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Usuari', '0001_initial'),
        ('LycuMain', '0006_curiositat_categoria_a_cusiositat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vots',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ha_votat', models.BooleanField(default=False)),
                ('tipus', models.BooleanField(default=True)),
                ('curiositat_votada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LycuMain.Curiositat')),
                ('usuari_vota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuari.Usuaris')),
            ],
        ),
    ]
